version: '3.8'
services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes: 
      - ./cache:/data


  web-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=cache:6379
      - LIMITER_IP=5
      - LIMITER_TOKEN=10
      - BLOCK_DURATION=5m
    depends_on:
      - cache
volumes:
  cache:
    driver: local